[package]
name = "bettervoxel_game_config"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_input = { version = "0.13.2", features = ["serialize"] }
bevy_transform = { version = "0.13.2", features = ["serialize"] }
bevy_math = { version = "0.13.2", features = ["serialize"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
smol_str = { version = "0.2.2", features = ["serde"] }